version = 3.8.4-RC3
# https://github.com/gvolpe/trading/blob/main/.scalafmt.conf

align.allowOverflow = true
align.preset = more
align.openParenCallSite = false
align.stripMargin = true

runner.dialect = scala3
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true


maxColumn                        = 120
indentOperator.preset            = spray
indentOperator.exemptScope       = all
spaces.inImportCurlyBraces       = true
rewrite.rules                    = [Imports, RedundantBraces, RedundantParens]
rewrite.imports.sort             = ascii
docstrings.blankFirstLine        = true
trailingCommas                   = preserve
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
docstrings.style                 = keep

fileOverride {
  "glob:**/build.sbt" {
    runner.dialect = scala213
  }
  "glob:**/project/**" {
    runner.dialect = scala213
  }
}
