rules = [
  DisableSyntax,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  OrganizeImports,
  RedundantSyntax
]

OrganizeImports {
  expandRelative = false
  groupedImports = Explode
  groups = [
    "scala."
    "ihoje."
    "com.pulumi."
    "*"
  ]
  removeUnused = true
}

DisableSyntax {
  noFinalize = true
  noImplicitConversion = true
  noImplicitObject = true
  noNullChecks = true
  noReturns = true
  noSemicolons = true
  noTabs = true
  noThrows = true
  noUniversalEquality = true
  noVars = false
  noXml = true
}